name: Build LXC Containers

on:
  workflow_dispatch:
    inputs:
      publish_all:
        description: '是否发布所有构建的镜像'
        required: false
        type: boolean
        default: true

jobs:
  build-centos-10-stream-amd64:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Install LXC dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y lxc lxc-templates bridge-utils curl tar sshpass

    - name: Configure LXC environment
      run: |
        sudo systemctl start lxc
        sudo lxc-checkconfig

    - name: Build LXC builder
      run: go build -o lxc-builder

    - name: Build CentOS 10 Stream amd64 container
      run: |
        ./lxc-builder build centos 10-Stream amd64
        
    - name: Test SSH connection
      run: |
        sleep 30
        CONTAINER_NAME=$(ls /var/lib/lxc/ | grep centos)
        CONTAINER_IP=$(sudo lxc-info -n $CONTAINER_NAME -i -H)
        echo "Container IP: $CONTAINER_IP"
        sshpass -p "github-actions-123" ssh -o StrictHostKeyChecking=no -o ConnectTimeout=30 root@$CONTAINER_IP "echo 'SSH connection successful'"

    - name: Publish container
      if: ${{ github.event.inputs.publish_all }}
      run: |
        CONTAINER_NAME=$(ls /var/lib/lxc/ | grep centos)
        ./lxc-builder publish $CONTAINER_NAME
        
    - name: Upload container artifact
      if: ${{ github.event.inputs.publish_all }}
      uses: actions/upload-artifact@v4
      with:
        name: lxc-container-centos-10-stream-amd64
        path: "*.tar.gz"
        retention-days: 7

    - name: Cleanup
      if: always()
      run: |
        sudo lxc-ls --running | xargs -r -I {} sudo lxc-stop -n {}
        sudo lxc-ls | xargs -r -I {} sudo lxc-destroy -n {} -f

  build-centos-10-stream-arm64:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Install LXC dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y lxc lxc-templates bridge-utils curl tar sshpass

    - name: Configure LXC environment
      run: |
        sudo systemctl start lxc
        sudo lxc-checkconfig

    - name: Build LXC builder
      run: go build -o lxc-builder

    - name: Build CentOS 10 Stream arm64 container
      run: |
        ./lxc-builder build centos 10-Stream arm64
        
    - name: Test SSH connection
      run: |
        sleep 30
        CONTAINER_NAME=$(ls /var/lib/lxc/ | grep centos)
        CONTAINER_IP=$(sudo lxc-info -n $CONTAINER_NAME -i -H)
        echo "Container IP: $CONTAINER_IP"
        sshpass -p "github-actions-123" ssh -o StrictHostKeyChecking=no -o ConnectTimeout=30 root@$CONTAINER_IP "echo 'SSH connection successful'"

    - name: Publish container
      if: ${{ github.event.inputs.publish_all }}
      run: |
        CONTAINER_NAME=$(ls /var/lib/lxc/ | grep centos)
        ./lxc-builder publish $CONTAINER_NAME
        
    - name: Upload container artifact
      if: ${{ github.event.inputs.publish_all }}
      uses: actions/upload-artifact@v4
      with:
        name: lxc-container-centos-10-stream-arm64
        path: "*.tar.gz"
        retention-days: 7

    - name: Cleanup
      if: always()
      run: |
        sudo lxc-ls --running | xargs -r -I {} sudo lxc-stop -n {}
        sudo lxc-ls | xargs -r -I {} sudo lxc-destroy -n {} -f

  build-centos-9-stream-amd64:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Install LXC dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y lxc lxc-templates bridge-utils curl tar sshpass

    - name: Configure LXC environment
      run: |
        sudo systemctl start lxc
        sudo lxc-checkconfig
        sudo brctl addbr lxcbr0 || true
        sudo ip addr add 10.0.3.1/24 dev lxcbr0
        sudo ip link set lxcbr0 up

    - name: Build LXC builder
      run: go build -o lxc-builder

    - name: Build CentOS 9 Stream amd64 container
      run: |
        ./lxc-builder build centos 9-Stream amd64
        
    - name: Test SSH connection
      run: |
        sleep 30
        CONTAINER_NAME=$(ls /var/lib/lxc/ | grep centos)
        CONTAINER_IP=$(sudo lxc-info -n $CONTAINER_NAME -i -H)
        echo "Container IP: $CONTAINER_IP"
        sshpass -p "github-actions-123" ssh -o StrictHostKeyChecking=no -o ConnectTimeout=30 root@$CONTAINER_IP "echo 'SSH connection successful'"

    - name: Publish container
      if: ${{ github.event.inputs.publish_all }}
      run: |
        CONTAINER_NAME=$(ls /var/lib/lxc/ | grep centos)
        ./lxc-builder publish $CONTAINER_NAME
        
    - name: Upload container artifact
      if: ${{ github.event.inputs.publish_all }}
      uses: actions/upload-artifact@v4
      with:
        name: lxc-container-centos-9-stream-amd64
        path: "*.tar.gz"
        retention-days: 7

    - name: Cleanup
      if: always()
      run: |
        sudo lxc-ls --running | xargs -r -I {} sudo lxc-stop -n {}
        sudo lxc-ls | xargs -r -I {} sudo lxc-destroy -n {} -f

  build-centos-9-stream-arm64:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Install LXC dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y lxc lxc-templates bridge-utils curl tar sshpass

    - name: Configure LXC environment
      run: |
        sudo systemctl start lxc
        sudo lxc-checkconfig
        sudo brctl addbr lxcbr0 || true
        sudo ip addr add 10.0.3.1/24 dev lxcbr0
        sudo ip link set lxcbr0 up

    - name: Build LXC builder
      run: go build -o lxc-builder

    - name: Build CentOS 9 Stream arm64 container
      run: |
        ./lxc-builder build centos 9-Stream arm64
        
    - name: Test SSH connection
      run: |
        sleep 30
        CONTAINER_NAME=$(ls /var/lib/lxc/ | grep centos)
        CONTAINER_IP=$(sudo lxc-info -n $CONTAINER_NAME -i -H)
        echo "Container IP: $CONTAINER_IP"
        sshpass -p "github-actions-123" ssh -o StrictHostKeyChecking=no -o ConnectTimeout=30 root@$CONTAINER_IP "echo 'SSH connection successful'"

    - name: Publish container
      if: ${{ github.event.inputs.publish_all }}
      run: |
        CONTAINER_NAME=$(ls /var/lib/lxc/ | grep centos)
        ./lxc-builder publish $CONTAINER_NAME
        
    - name: Upload container artifact
      if: ${{ github.event.inputs.publish_all }}
      uses: actions/upload-artifact@v4
      with:
        name: lxc-container-centos-9-stream-arm64
        path: "*.tar.gz"
        retention-days: 7

    - name: Cleanup
      if: always()
      run: |
        sudo lxc-ls --running | xargs -r -I {} sudo lxc-stop -n {}
        sudo lxc-ls | xargs -r -I {} sudo lxc-destroy -n {} -f
